apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "item-service.fullname" . }}
  labels:
    {{- include "item-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "item-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        # Automatically roll deployment when a configmap file changes
        # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        checksum/datasource-config: {{ include (print $.Template.BasePath "/datasource-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "item-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "item-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.global.itemService.servicePort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: server.port
            value: {{ .Values.global.itemService.servicePort | quote }}
          envFrom:
          - configMapRef:
              name: {{ include "item-service.datasourceConfigmapName" . }}
          - configMapRef:
              name: {{ .Values.global.activemqBrokerConfigMapName }}
          - configMapRef:
              name: {{ .Values.global.sharedSettingsConfigMapName }}
          volumeMounts:
          - name: application-config
            mountPath: /app/config
            readOnly: true
      volumes:
        - name: application-config
          configMap:
            # Name of the ConfigMap containing the files we want
            # to add to the container
            name: {{ .Values.global.jmsPropertiesConfigMapName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
