version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: echo "Skipping tests on gh-pages branch"

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
