{{- if .Values.realmSecretEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-realm-secret
  labels:
    {{- include "keycloak-config.labels" . | nindent 4 }}
    {{- include "keycloak-config.keycloakRealmLabel" . | nindent 4 }}
  annotations:
    description: >
      this secret needs to be created in and have different values in each
      different kube namespace because customers will each be working in their own namespace
      and their own Keycloak realm.
data:
  # Password for an admin of this realm. Username is defined in keycloak-realm-config
  grails.plugin.springsecurity.rest.keycloak.realmAdminPassword: {{ required "realmAdminPassword cannot be emtpy" .Values.realmAdminPassword | b64enc }}
  # Client secret, which is going to be different in each k8s realm
  grails.plugin.springsecurity.rest.keycloak.secret: {{ required "clientSecret cannot be emtpy" .Values.clientSecret | b64enc }}
{{- end }}
