apiVersion: v1
kind: Secret
metadata:
  name: keycloak-shared-secret
  labels:
    {{- include "keycloak-config.labels" . | nindent 4 }}
  annotations:
    description: >
      This secret will have the same values in each kubernetes namespace.
      In addition to being created in the Keycloak namespace for the helm keycloak installation to access,
      this gets created in each client namespace as well.
data:
  # The username for the database that Keycloak connects to
  databaseUsername: {{ .Values.databaseUsername | b64enc }}
  # The password for the database that Keycloak connects to
  databasePassword: {{ required "databasePassword cannot be emtpy" .Values.databasePassword | b64enc }}
  grails.plugin.springsecurity.rest.keycloak.masterAdminPassword: {{ required "masterAdminPassword cannot be emtpy" .Values.masterAdminPassword | b64enc }}

