# This will have different values for each client/namespace
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.userServiceConfigmapName" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
  annotations:
    description: >
      Contains configuration settings specifically for the User Service Grails application,
      which will be supplied to the User Service Grails application as environment variables.
data:
  {{- if .Values.mail.password }}
  grails.mail.password: {{ .Values.mail.password | quote }}
  {{- end }}
