---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [master, deploy, gh-pages]
  pull_request:
    branches: [master]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7
        env:
          LINTER_RULES_PATH: "."
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Exclude CHANGELOG.md and other files
          FILTER_REGEX_EXCLUDE: "(CHANGELOG.md)|(charts/thub/ci/test-values.yaml)"
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          # Kubeconform fails with helm charts
          VALIDATE_KUBERNETES_KUBECONFORM: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_YAML: false
          VALIDATE_YAML_PRETTIER: false
      # Run specific linters and only output warnings. Each linter run here should not be run in the action above.
      - name: Lint Code Base for Warnings
        uses: super-linter/super-linter/slim@v7
        env:
          LINTER_RULES_PATH: "."
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Flag to have the linter complete with exit code 0 even if errors were detected.
          DISABLE_ERRORS: true
          VALIDATE_JSCPD: true
